language: python
install:
  - pip install -r requirements.txt
script:
  - python -m unittest unitTest.py

deploy:
  provider: lambda
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  function_name: "DreamBroker-AnalyzeText"
  runtime: "python3.7"
  edge: true # opt in to dpl v2..