language: python
deploy:
  provider: lambda
  access_key_id: <encrypted access_key_id>
  secret_access_key: <encrypted secret_access_key>
  function_name: "DreamBroker-AnalyzeText"
  runtime: "python3.7"
  edge: true # opt in to dpl v2..