language: python
install:
  - pip install -r requirements.txt
script:
  - python -m unittest unitTest.py

deploy:
  provider: lambda
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  function_name: "DreamBroker-AnalyzeText"
  runtime: "python3.7"
  handler_name: "lambda_handler"
  zip: "./analyzeText.py"
  role: "arn:aws:iam::981321371788:role/service-role/DreamBroker-AnalyzeText-role-nq32qasd"
  on:
    branch: main
  edge: true # opt in to dpl v2..