language: python
install:
  - pip install -r requirements.txt
script:
  - python -m unittest unitTest.py

deploy:
  provider: lambda
  region: "eu-central-1"
  function_name: "DreamBroker-AnalyzeText"
  runtime: "python3.7"
  role: "arn:aws:iam::981321371788:role/service-role/DreamBroker-AnalyzeText-role-nq32qasd" 
  handler_name: "lambda_handler"
  on: all_branches: true
 
